# Generated by Django 5.2.9 on 2026-01-24 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0011_alter_transaction_transaction_type_and_more'),
        ('rentals', '0005_extend_lat_lng_precision'),
        ('stations', '0006_extend_lat_lng_precision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner_type', models.CharField(choices=[('FRANCHISE', 'Franchise'), ('VENDOR', 'Vendor')], max_length=20)),
                ('vendor_type', models.CharField(blank=True, choices=[('REVENUE', 'Revenue Vendor'), ('NON_REVENUE', 'Non-Revenue Vendor')], help_text='Only applicable for VENDOR partner_type', max_length=20, null=True)),
                ('code', models.CharField(help_text='Partner code e.g., FR-001, VN-001', max_length=20, unique=True)),
                ('business_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('upfront_amount', models.DecimalField(decimal_places=2, default=0, help_text='One-time upfront payment received from Franchise', max_digits=12)),
                ('revenue_share_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Franchise revenue share % (y% of station net revenue)', max_digits=5, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Available balance for payout', max_digits=12)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, help_text='Lifetime total earnings', max_digits=12)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_partners', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='NULL for ChargeGhar-level, FK to Franchise for sub-vendors', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_partners', to='partners.partner')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'db_table': 'partners',
            },
        ),
        migrations.CreateModel(
            name='PartnerIotHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('EJECT', 'Eject Powerbank'), ('REBOOT', 'Reboot Station'), ('CHECK', 'Check Status'), ('WIFI_SCAN', 'WiFi Scan'), ('WIFI_CONNECT', 'WiFi Connect'), ('VOLUME', 'Volume Control'), ('MODE', 'SIM/WiFi Mode')], max_length=20)),
                ('performed_from', models.CharField(choices=[('MOBILE_APP', 'Mobile App'), ('DASHBOARD', 'Dashboard'), ('ADMIN_PANEL', 'Admin Panel')], max_length=20)),
                ('powerbank_sn', models.CharField(blank=True, help_text='Powerbank serial number (for EJECT)', max_length=100, null=True)),
                ('slot_number', models.IntegerField(blank=True, help_text='Slot number (for EJECT)', null=True)),
                ('is_free_ejection', models.BooleanField(default=False, help_text='True if vendor free daily ejection')),
                ('is_successful', models.BooleanField(help_text='Whether the action was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed', null=True)),
                ('request_payload', models.JSONField(default=dict, help_text='Request payload sent to IoT')),
                ('response_data', models.JSONField(default=dict, help_text='Response data from IoT')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_history', to='partners.partner')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_iot_actions', to=settings.AUTH_USER_MODEL)),
                ('rental', models.ForeignKey(blank=True, help_text='Related rental (for free ejection)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_iot_actions', to='rentals.rental')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_iot_history', to='stations.station')),
            ],
            options={
                'verbose_name': 'Partner IoT History',
                'verbose_name_plural': 'Partner IoT Histories',
                'db_table': 'partner_iot_history',
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout_type', models.CharField(choices=[('CHARGEGHAR_TO_FRANCHISE', 'ChargeGhar to Franchise'), ('CHARGEGHAR_TO_VENDOR', 'ChargeGhar to Vendor'), ('FRANCHISE_TO_VENDOR', 'Franchise to Vendor')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Requested payout amount', max_digits=12)),
                ('vat_deducted', models.DecimalField(decimal_places=2, default=0, help_text='VAT deducted (always 0 - already in balance)', max_digits=12)),
                ('service_charge_deducted', models.DecimalField(decimal_places=2, default=0, help_text='Service charge deducted (always 0 - already in balance)', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Net payout amount (equals amount)', max_digits=12)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reference_id', models.CharField(help_text='Internal payout reference', max_length=50, unique=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='partners.partner')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payout Request',
                'verbose_name_plural': 'Payout Requests',
                'db_table': 'payout_requests',
            },
        ),
        migrations.CreateModel(
            name='RevenueDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Total transaction amount', max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, help_text='VAT deducted at ChargeGhar level', max_digits=12)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, help_text='Service charge deducted at ChargeGhar level', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='gross - vat - service_charge', max_digits=12)),
                ('chargeghar_share', models.DecimalField(decimal_places=2, default=0, help_text='ChargeGhar retains this amount', max_digits=12)),
                ('franchise_share', models.DecimalField(decimal_places=2, default=0, help_text='Franchise share amount', max_digits=12)),
                ('vendor_share', models.DecimalField(decimal_places=2, default=0, help_text='Vendor share amount', max_digits=12)),
                ('is_distributed', models.BooleanField(default=False, help_text='Has this been added to partner balances?')),
                ('distributed_at', models.DateTimeField(blank=True, help_text='When partner balances were updated', null=True)),
                ('calculation_details', models.JSONField(default=dict, help_text='Detailed breakdown of calculation for audit')),
                ('franchise', models.ForeignKey(blank=True, help_text='Franchise partner (if station owned by franchise)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='franchise_revenue_distributions', to='partners.partner')),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_distributions', to='rentals.rental')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_distributions', to='stations.station')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_distributions', to='payments.transaction')),
                ('vendor', models.ForeignKey(blank=True, help_text='Vendor partner (if station operated by vendor)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_revenue_distributions', to='partners.partner')),
            ],
            options={
                'verbose_name': 'Revenue Distribution',
                'verbose_name_plural': 'Revenue Distributions',
                'db_table': 'revenue_distributions',
            },
        ),
        migrations.CreateModel(
            name='StationDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distribution_type', models.CharField(choices=[('CHARGEGHAR_TO_FRANCHISE', 'ChargeGhar to Franchise'), ('CHARGEGHAR_TO_VENDOR', 'ChargeGhar to Vendor'), ('FRANCHISE_TO_VENDOR', 'Franchise to Vendor')], max_length=30)),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_station_distributions', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_distributions', to='partners.partner')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_distributions', to='stations.station')),
            ],
            options={
                'verbose_name': 'Station Distribution',
                'verbose_name_plural': 'Station Distributions',
                'db_table': 'station_distributions',
            },
        ),
        migrations.CreateModel(
            name='StationRevenueShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revenue_model', models.CharField(choices=[('PERCENTAGE', 'Percentage of Net Revenue'), ('FIXED', 'Fixed Monthly Amount')], max_length=20)),
                ('partner_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Vendor share percentage (e.g., 10.00 for 10%)', max_digits=5, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed monthly amount vendor pays to owner', max_digits=12, null=True)),
                ('distribution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_share', to='partners.stationdistribution')),
            ],
            options={
                'verbose_name': 'Station Revenue Share',
                'verbose_name_plural': 'Station Revenue Shares',
                'db_table': 'station_revenue_shares',
            },
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['partner_type', 'status'], name='partners_partner_078717_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['parent'], name='partners_parent__5f229b_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['code'], name='partners_code_4a2745_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['status'], name='partners_status_6458e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.CheckConstraint(condition=models.Q(('partner_type', 'FRANCHISE'), models.Q(('partner_type', 'VENDOR'), ('vendor_type__isnull', False)), _connector='OR'), name='vendor_must_have_vendor_type'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.CheckConstraint(condition=models.Q(('partner_type', 'VENDOR'), models.Q(('partner_type', 'FRANCHISE'), ('vendor_type__isnull', True)), _connector='OR'), name='franchise_cannot_have_vendor_type'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.CheckConstraint(condition=models.Q(('partner_type', 'VENDOR'), models.Q(('partner_type', 'FRANCHISE'), ('parent__isnull', True)), _connector='OR'), name='franchise_must_be_under_chargeghar'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.CheckConstraint(condition=models.Q(('revenue_share_percent__isnull', True), models.Q(('revenue_share_percent__gte', 0), ('revenue_share_percent__lte', 100)), _connector='OR'), name='valid_revenue_share_percent'),
        ),
        migrations.AddIndex(
            model_name='partneriothistory',
            index=models.Index(fields=['partner', 'action_type', 'created_at'], name='partner_iot_partner_0a98bd_idx'),
        ),
        migrations.AddIndex(
            model_name='partneriothistory',
            index=models.Index(fields=['station', 'created_at'], name='partner_iot_station_e4815e_idx'),
        ),
        migrations.AddIndex(
            model_name='partneriothistory',
            index=models.Index(fields=['action_type', 'is_successful'], name='partner_iot_action__2ade52_idx'),
        ),
        migrations.AddIndex(
            model_name='partneriothistory',
            index=models.Index(fields=['created_at'], name='partner_iot_created_285413_idx'),
        ),
        migrations.AddConstraint(
            model_name='partneriothistory',
            constraint=models.CheckConstraint(condition=models.Q(('action_type__in', ['EJECT', 'REBOOT', 'CHECK', 'WIFI_SCAN', 'WIFI_CONNECT', 'VOLUME', 'MODE'])), name='valid_iot_action_type'),
        ),
        migrations.AddConstraint(
            model_name='partneriothistory',
            constraint=models.CheckConstraint(condition=models.Q(('performed_from__in', ['MOBILE_APP', 'DASHBOARD', 'ADMIN_PANEL'])), name='valid_performed_from'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['partner', 'status'], name='payout_requ_partner_06b05b_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['payout_type', 'status'], name='payout_requ_payout__1d6db6_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['status'], name='payout_requ_status_75a6f8_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['created_at'], name='payout_requ_created_f39fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['reference_id'], name='payout_requ_referen_f7cc4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='payoutrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payout_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payoutrequest',
            constraint=models.CheckConstraint(condition=models.Q(('payout_type__in', ['CHARGEGHAR_TO_FRANCHISE', 'CHARGEGHAR_TO_VENDOR', 'FRANCHISE_TO_VENDOR'])), name='valid_payout_type'),
        ),
        migrations.AddConstraint(
            model_name='payoutrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED', 'PROCESSING', 'COMPLETED', 'REJECTED'])), name='valid_payout_status'),
        ),
        migrations.AddIndex(
            model_name='revenuedistribution',
            index=models.Index(fields=['transaction'], name='revenue_dis_transac_44e142_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuedistribution',
            index=models.Index(fields=['station', 'created_at'], name='revenue_dis_station_f3c5a3_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuedistribution',
            index=models.Index(fields=['franchise', 'is_distributed'], name='revenue_dis_franchi_9f2aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuedistribution',
            index=models.Index(fields=['vendor', 'is_distributed'], name='revenue_dis_vendor__e19ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuedistribution',
            index=models.Index(fields=['is_distributed'], name='revenue_dis_is_dist_5194dd_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuedistribution',
            index=models.Index(fields=['created_at'], name='revenue_dis_created_d3cef0_idx'),
        ),
        migrations.AddIndex(
            model_name='stationdistribution',
            index=models.Index(fields=['station', 'is_active'], name='station_dis_station_c382bc_idx'),
        ),
        migrations.AddIndex(
            model_name='stationdistribution',
            index=models.Index(fields=['partner', 'is_active'], name='station_dis_partner_fce1c2_idx'),
        ),
        migrations.AddIndex(
            model_name='stationdistribution',
            index=models.Index(fields=['distribution_type'], name='station_dis_distrib_de1749_idx'),
        ),
        migrations.AddIndex(
            model_name='stationdistribution',
            index=models.Index(fields=['is_active'], name='station_dis_is_acti_14c933_idx'),
        ),
        migrations.AddConstraint(
            model_name='stationdistribution',
            constraint=models.CheckConstraint(condition=models.Q(('distribution_type__in', ['CHARGEGHAR_TO_FRANCHISE', 'CHARGEGHAR_TO_VENDOR', 'FRANCHISE_TO_VENDOR'])), name='valid_distribution_type'),
        ),
        migrations.AddIndex(
            model_name='stationrevenueshare',
            index=models.Index(fields=['distribution'], name='station_rev_distrib_d4f5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='stationrevenueshare',
            index=models.Index(fields=['revenue_model'], name='station_rev_revenue_da6b76_idx'),
        ),
        migrations.AddConstraint(
            model_name='stationrevenueshare',
            constraint=models.CheckConstraint(condition=models.Q(('revenue_model__in', ['PERCENTAGE', 'FIXED'])), name='valid_revenue_model'),
        ),
        migrations.AddConstraint(
            model_name='stationrevenueshare',
            constraint=models.CheckConstraint(condition=models.Q(('revenue_model', 'FIXED'), models.Q(('revenue_model', 'PERCENTAGE'), ('partner_percent__isnull', False)), _connector='OR'), name='percentage_model_must_have_percent'),
        ),
        migrations.AddConstraint(
            model_name='stationrevenueshare',
            constraint=models.CheckConstraint(condition=models.Q(('revenue_model', 'PERCENTAGE'), models.Q(('revenue_model', 'FIXED'), ('fixed_amount__isnull', False)), _connector='OR'), name='fixed_model_must_have_amount'),
        ),
        migrations.AddConstraint(
            model_name='stationrevenueshare',
            constraint=models.CheckConstraint(condition=models.Q(('partner_percent__isnull', True), models.Q(('partner_percent__gte', 0), ('partner_percent__lte', 100)), _connector='OR'), name='valid_partner_percent'),
        ),
        migrations.AddConstraint(
            model_name='stationrevenueshare',
            constraint=models.CheckConstraint(condition=models.Q(('fixed_amount__isnull', True), ('fixed_amount__gte', 0), _connector='OR'), name='valid_fixed_amount'),
        ),
    ]
