# Generated by Django 5.2.5 on 2026-01-30 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuedistribution',
            name='is_reversal',
            field=models.BooleanField(default=False, help_text='Is this a reversal distribution (negative amounts for refunds)?'),
        ),
        migrations.AddField(
            model_name='revenuedistribution',
            name='reversal_reason',
            field=models.CharField(blank=True, choices=[('FULL_REFUND', 'Full Refund'), ('PARTIAL_REFUND', 'Partial Refund')], help_text='Reason for reversal', max_length=50),
        ),
        migrations.AddField(
            model_name='revenuedistribution',
            name='reversed_distribution',
            field=models.ForeignKey(blank=True, help_text='Original distribution being reversed (for refunds)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='partners.revenuedistribution'),
        ),
    ]
