-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgBZ8IOFSKOhjsalWl
0UxZGhKk1nCKsCROpd1YU7+ZTumgCgYIKoZIzj0DAQehRANCAARRpWy0GEWAUcEJ
SHMBXWeeBKUSnur0wlOM8iPOgarKczxtVZWMEjaxcIN7dE30sX4y8OoLFJOz0roW
spZYEUax
-----END PRIVATE KEY-----