# Generated by Django 5.2.5 on 2026-01-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LateFeeConfiguration',
        ),
    ]
