"""
Common Serializers
Auto-generated by split_serializer.py
"""

from __future__ import annotations
from api.admin.models import SystemLog
from decimal import Decimal
from rest_framework import serializers


class SystemLogSerializer(serializers.ModelSerializer):
    """Serializer for system logs"""
    level_display = serializers.CharField(source='get_level_display', read_only=True)
    
    class Meta:
        model = SystemLog
        fields = [
            'id', 'level', 'level_display', 'module', 'message', 
            'context', 'trace_id', 'created_at'
        ]
        read_only_fields = ['id', 'created_at']



class ToggleMaintenanceSerializer(serializers.Serializer):
    """Serializer for toggling maintenance mode"""
    is_maintenance = serializers.BooleanField()
    reason = serializers.CharField(max_length=500)



class RemoteCommandSerializer(serializers.Serializer):
    """Serializer for sending remote commands"""
    command = serializers.ChoiceField(choices=[
        'REBOOT', 'UNLOCK_SLOT', 'LOCK_SLOT', 'UPDATE_FIRMWARE',
        'SYNC_TIME', 'CLEAR_CACHE', 'RESET_HARDWARE'
    ])
    parameters = serializers.JSONField(default=dict)



class SystemHealthSerializer(serializers.Serializer):
    """Serializer for system health (response only)"""
    database_status = serializers.CharField()
    redis_status = serializers.CharField()
    celery_status = serializers.CharField()
    storage_status = serializers.CharField()
    response_time_avg = serializers.FloatField()
    error_rate = serializers.FloatField()
    uptime_percentage = serializers.FloatField()
    cpu_usage = serializers.FloatField()
    memory_usage = serializers.FloatField()
    disk_usage = serializers.FloatField()
    pending_tasks = serializers.IntegerField()
    failed_tasks = serializers.IntegerField()
    last_updated = serializers.DateTimeField()



class SystemLogFiltersSerializer(serializers.Serializer):
    """Serializer for system log filters"""
    level = serializers.ChoiceField(
        choices=SystemLog.LogLevelChoices.choices,
        required=False
    )
    module = serializers.CharField(required=False)
    search = serializers.CharField(required=False)
    start_date = serializers.DateTimeField(required=False)
    end_date = serializers.DateTimeField(required=False)
    page = serializers.IntegerField(default=1, min_value=1)
    page_size = serializers.IntegerField(default=50, min_value=1, max_value=200)



class RevenueOverTimeQuerySerializer(serializers.Serializer):
    """Query parameters for revenue over time analytics"""
    period = serializers.ChoiceField(
        choices=['daily', 'weekly', 'monthly'],
        required=True,
        help_text="Aggregation period: daily, weekly, or monthly"
    )
    start_date = serializers.DateField(
        required=False,
        help_text="Start date (default: 180 days ago)"
    )
    end_date = serializers.DateField(
        required=False,
        help_text="End date (default: today)"
    )
    transaction_type = serializers.ChoiceField(
        choices=['TOPUP', 'RENTAL', 'RENTAL_DUE', 'REFUND', 'FINE'],
        required=False,
        help_text="Filter by transaction type"
    )



class RevenueChartDataSerializer(serializers.Serializer):
    """Single data point for revenue chart"""
    date = serializers.DateField()
    label = serializers.CharField()
    total_revenue = serializers.FloatField()
    rental_revenue = serializers.FloatField()
    rental_due_revenue = serializers.FloatField()
    topup_revenue = serializers.FloatField()
    fine_revenue = serializers.FloatField()
    transaction_count = serializers.IntegerField()



class RevenueSummarySerializer(serializers.Serializer):
    """Summary statistics for revenue over time"""
    avg_per_period = serializers.FloatField()
    peak_month = serializers.CharField(allow_null=True)
    peak_revenue = serializers.FloatField()
    growth_rate = serializers.FloatField(allow_null=True)



class RevenueOverTimeResponseSerializer(serializers.Serializer):
    """Response format for revenue over time endpoint"""
    period = serializers.CharField()
    start_date = serializers.DateField()
    end_date = serializers.DateField()
    currency = serializers.CharField()
    total_revenue = serializers.FloatField()
    chart_data = RevenueChartDataSerializer(many=True)
    summary = RevenueSummarySerializer()
