"""
User Serializers
Auto-generated by split_serializer.py
"""

from __future__ import annotations
from decimal import Decimal
from django.core.exceptions import ObjectDoesNotExist
from rest_framework import serializers

from api.admin.models import AdminProfile
from api.user.auth.models import User, UserKYC, UserProfile


class AdminProfileSerializer(serializers.ModelSerializer):
    """Serializer for admin profiles"""
    username = serializers.CharField(source='user.username', read_only=True)
    email = serializers.CharField(source='user.email', read_only=True)
    created_by_username = serializers.CharField(source='created_by.username', read_only=True)
    is_super_admin = serializers.BooleanField(read_only=True)
    
    class Meta:
        model = AdminProfile
        fields = [
            'id', 'role', 'is_active', 'is_super_admin',
            'created_at', 'updated_at',
            'username', 'email', 'created_by_username'
        ]
        read_only_fields = ['id', 'created_at', 'updated_at']



class AdminProfileCreateSerializer(serializers.Serializer):
    """Serializer for creating admin profiles"""
    user = serializers.IntegerField()
    role = serializers.ChoiceField(choices=AdminProfile.RoleChoices.choices)
    password = serializers.CharField(write_only=True, required=True, min_length=8, max_length=128)



class AdminProfileUpdateSerializer(serializers.Serializer):
    """Serializer for updating admin profile (role, password, is_active)"""
    role = serializers.ChoiceField(
        choices=AdminProfile.RoleChoices.choices,
        required=False,
        help_text="Update admin role"
    )
    new_password = serializers.CharField(
        min_length=8,
        max_length=128,
        required=False,
        write_only=True,
        help_text="Update password (minimum 8 characters)"
    )
    is_active = serializers.BooleanField(
        required=False,
        help_text="Activate (true) or deactivate (false) admin"
    )
    reason = serializers.CharField(
        max_length=500,
        required=False,
        allow_blank=True,
        help_text="Reason for deactivation/activation"
    )



class AdminProfileActionSerializer(serializers.Serializer):
    """Serializer for admin profile actions (activate/deactivate)"""
    reason = serializers.CharField(max_length=500, required=False, allow_blank=True)



class AdminUserListSerializer(serializers.Serializer):
    """Serializer for user list filters"""
    status = serializers.CharField(required=False)
    search = serializers.CharField(required=False)
    start_date = serializers.DateTimeField(required=False)
    end_date = serializers.DateTimeField(required=False)
    page = serializers.IntegerField(default=1, min_value=1)
    page_size = serializers.IntegerField(default=20, min_value=1, max_value=100)


class AdminUserResponseSerializer(serializers.ModelSerializer):
    """Admin-focused user serializer with explicit profile and KYC mapping."""
    profile_complete = serializers.SerializerMethodField()
    kyc_status = serializers.SerializerMethodField()
    profile = serializers.SerializerMethodField()

    class Meta:
        model = User
        fields = [
            'id', 'email', 'phone_number', 'username', 'profile_picture',
            'referral_code', 'status', 'is_active', 'date_joined', 'last_login',
            'profile_complete', 'kyc_status', 'profile', 'social_provider',
        ]
        read_only_fields = fields

    def _get_profile(self, obj: User) -> UserProfile | None:
        try:
            profile = obj.profile
        except (AttributeError, ObjectDoesNotExist):
            profile = None

        if profile is None:
            profile = UserProfile.objects.filter(user_id=obj.id).first()

        return profile

    def _get_kyc(self, obj: User) -> UserKYC | None:
        try:
            kyc = obj.kyc
        except (AttributeError, ObjectDoesNotExist):
            kyc = None

        if kyc is None:
            kyc = UserKYC.objects.filter(user_id=obj.id).first()

        return kyc

    def get_profile_complete(self, obj: User) -> bool:
        profile = self._get_profile(obj)
        return bool(profile and profile.is_profile_complete)

    def get_kyc_status(self, obj: User) -> str:
        kyc = self._get_kyc(obj)
        return kyc.status if kyc else 'NOT_SUBMITTED'

    def get_profile(self, obj: User) -> dict[str, object]:
        profile = self._get_profile(obj)
        if not profile:
            return {
                'full_name': None,
                'date_of_birth': None,
                'address': None,
                'is_profile_complete': False,
            }

        return {
            'full_name': profile.full_name,
            'date_of_birth': profile.date_of_birth,
            'address': profile.address,
            'is_profile_complete': profile.is_profile_complete,
        }



class UpdateUserStatusSerializer(serializers.Serializer):
    """Serializer for updating user status"""
    status = serializers.ChoiceField(choices=['ACTIVE', 'BANNED', 'INACTIVE'])
    reason = serializers.CharField(max_length=500)



class AddUserBalanceSerializer(serializers.Serializer):
    """Serializer for adding user balance"""
    amount = serializers.DecimalField(max_digits=10, decimal_places=2, min_value=Decimal('0.01'))
    reason = serializers.CharField(max_length=500)



class TransactionUserSerializer(serializers.Serializer):
    """User info in transaction response"""
    id = serializers.UUIDField()
    username = serializers.CharField()
    email = serializers.EmailField()
