# Generated by Django 5.2.5 on 2026-01-31 17:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0006_extend_lat_lng_precision'),
    ]

    operations = [
        migrations.CreateModel(
            name='IotSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_uuid', models.CharField(max_length=100)),
                ('sync_type', models.CharField(choices=[('STATUS', 'Status Update'), ('FULL', 'Full Sync'), ('RETURNED', 'Return Event')], max_length=20)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=10)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_sync_logs', to='stations.station')),
            ],
            options={
                'verbose_name': 'IoT Sync Log',
                'verbose_name_plural': 'IoT Sync Logs',
                'db_table': 'iot_sync_logs',
                'indexes': [models.Index(fields=['station', 'sync_type', 'created_at'], name='iot_sync_lo_station_4342a5_idx'), models.Index(fields=['device_uuid', 'created_at'], name='iot_sync_lo_device__b69db8_idx'), models.Index(fields=['status', 'created_at'], name='iot_sync_lo_status_8198b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='StationStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], max_length=20)),
                ('previous_status', models.CharField(blank=True, choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], max_length=20, null=True)),
                ('changed_at', models.DateTimeField()),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('triggered_by', models.CharField(choices=[('SYNC', 'IoT Sync'), ('HEARTBEAT', 'Heartbeat'), ('MANUAL', 'Manual Check'), ('TIMEOUT', 'Connection Timeout')], max_length=20)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='stations.station')),
            ],
            options={
                'verbose_name': 'Station Status History',
                'verbose_name_plural': 'Station Status Histories',
                'db_table': 'station_status_history',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['station', 'changed_at'], name='station_sta_station_de71fa_idx'), models.Index(fields=['status', 'changed_at'], name='station_sta_status_145b4e_idx')],
            },
        ),
    ]
