"""
Service for coupon operations
============================================================

This module contains service classes for service for coupon operations.

Auto-generated by Service Separator
Date: 2025-10-18 23:21:06
"""
from __future__ import annotations

import random
import string
from typing import Dict, Any, List
from django.core.cache import cache
from django.db import IntegrityError, transaction
from django.utils import timezone
from django.db.models import Q
from api.common.services.base import CRUDService, ServiceException
from api.common.utils.helpers import paginate_queryset
from api.user.promotions.models import Coupon, CouponUsage

class CouponService(CRUDService):
    """Service for coupon operations"""
    model = Coupon
    PUBLIC_ACTIVE_COUPONS_CACHE_KEY = "promotions:public:active_coupons"

    @classmethod
    def invalidate_public_active_coupons_cache(cls) -> None:
        """Clear cached public coupon list."""
        cache.delete(cls.PUBLIC_ACTIVE_COUPONS_CACHE_KEY)

    def get_public_active_coupons(self) -> List[Coupon]:
        """Get currently active, valid, public coupons for user discovery."""
        try:
            now = timezone.now()
            coupons = Coupon.objects.filter(
                status=Coupon.StatusChoices.ACTIVE,
                is_public=True,
                valid_from__lte=now,
                valid_until__gte=now
            ).order_by('-points_value')

            return coupons

        except Exception as e:
            self.log_error(f"Failed to get public active coupons: {str(e)}")
            return []
    
    def get_active_coupons(self) -> List[Coupon]:
        """Backward-compatible alias for public active coupons."""
        return self.get_public_active_coupons()
    
    def validate_coupon(self, coupon_code: str, user) -> Dict[str, Any]:
        """Validate if a coupon can be used by the user"""
        try:
            # Convert code to uppercase and strip whitespace
            coupon_code = coupon_code.strip().upper()
            
            coupon = Coupon.objects.select_related().get(code=coupon_code)
            
            now = timezone.now()
            
            # Check if coupon exists and is active
            if not coupon or coupon.status != Coupon.StatusChoices.ACTIVE:
                return {
                    'valid': False,
                    'coupon_code': coupon_code,
                    'points_value': 0,
                    'message': 'Invalid or inactive coupon code',
                    'can_use': False,
                    'uses_remaining': 0
                }
            
            # Check date validity
            if now < coupon.valid_from or now > coupon.valid_until:
                return {
                    'valid': False,
                    'coupon_code': coupon_code,
                    'points_value': 0,
                    'message': 'Coupon has expired or is not yet valid',
                    'can_use': False,
                    'uses_remaining': 0
                }
            
            # Check user's usage count
            user_usage_count = CouponUsage.objects.filter(
                coupon=coupon,
                user=user
            ).count()
            
            uses_remaining = max(0, coupon.max_uses_per_user - user_usage_count)
            
            if uses_remaining <= 0:
                return {
                    'valid': True,
                    'coupon_code': coupon_code,
                    'points_value': coupon.points_value,
                    'message': 'You have already used this coupon the maximum number of times',
                    'can_use': False,
                    'uses_remaining': 0
                }
            
            return {
                'valid': True,
                'coupon_code': coupon_code,
                'points_value': coupon.points_value,
                'message': f'Coupon is valid! You will receive {coupon.points_value} points.',
                'can_use': True,
                'uses_remaining': uses_remaining
            }
            
        except Coupon.DoesNotExist:
            return {
                'valid': False,
                'coupon_code': coupon_code,
                'points_value': 0,
                'message': 'Invalid coupon code',
                'can_use': False,
                'uses_remaining': 0
            }
        except Exception as e:
            self.log_error(f"Failed to validate coupon: {str(e)}")
            raise ServiceException("Failed to validate coupon")
    
    @transaction.atomic
    def apply_coupon(self, coupon_code: str, user) -> Dict[str, Any]:
        """Apply coupon and award points to user"""
        try:
            coupon_code = coupon_code.strip().upper()

            # Lock coupon row to reduce race conditions around usage-limit checks.
            coupon = Coupon.objects.select_for_update().get(code=coupon_code)

            # Validate coupon state and date window.
            validation = self.validate_coupon(coupon_code, user)
            if not validation['can_use']:
                raise ServiceException(
                    detail=validation['message'],
                    code="coupon_not_usable"
                )

            # Re-check usage count within the transaction before write.
            user_usage_count = CouponUsage.objects.filter(
                coupon=coupon,
                user=user,
            ).count()
            if user_usage_count >= coupon.max_uses_per_user:
                raise ServiceException(
                    detail='You have already used this coupon the maximum number of times',
                    code="coupon_not_usable"
                )

            # Create coupon usage record.
            coupon_usage = CouponUsage.objects.create(
                coupon=coupon,
                user=user,
                points_awarded=coupon.points_value
            )

            # Award points to user.
            from api.user.points.services import award_points

            award_points(
                user=user,
                points=coupon.points_value,
                source='COUPON',
                description=f'Coupon applied: {coupon.name}',
                async_send=False,  # Immediate for coupon redemption
                coupon_code=coupon.code,
                coupon_usage_id=str(coupon_usage.id)
            )

            # Send coupon notification using universal notification system.
            try:
                from api.user.notifications.services import notify
                notify(
                    user=user,
                    template_slug='coupon_applied',
                    async_send=True,  # Send asynchronously
                    coupon_code=coupon.code,
                    points=coupon.points_value
                )
            except Exception as e:
                # Notification failure shouldn't block coupon application.
                self.log_warning(f"Could not send coupon notification: {str(e)}")

            self.log_info(f"Coupon applied: {coupon.code} by {user.username}")

            return {
                'success': True,
                'coupon_code': coupon.code,
                'coupon_name': coupon.name,
                'points_awarded': coupon.points_value,
                'message': f'Coupon applied successfully! You received {coupon.points_value} points.'
            }

        except Coupon.DoesNotExist:
            raise ServiceException(
                detail="Invalid coupon code",
                code="invalid_coupon"
            )
        except IntegrityError:
            raise ServiceException(
                detail='You have already used this coupon the maximum number of times',
                code="coupon_not_usable"
            )
        except Exception as e:
            self.handle_service_error(e, "Failed to apply coupon")
    
    def get_user_coupon_history(self, user, page: int = 1, page_size: int = 20) -> Dict[str, Any]:
        """Get user's coupon usage history"""
        try:
            queryset = CouponUsage.objects.filter(user=user).select_related('coupon')
            queryset = queryset.order_by('-used_at')
            
            return paginate_queryset(queryset, page, page_size)
            
        except Exception as e:
            self.handle_service_error(e, "Failed to get user coupon history")
    
    @transaction.atomic
    def create_coupon(self, code: str, name: str, points_value: int, max_uses_per_user: int,
                     valid_from: timezone.datetime, valid_until: timezone.datetime,
                     admin_user, is_public: bool = True) -> Coupon:
        """Create new coupon (Admin)"""
        try:
            coupon = Coupon.objects.create(
                code=code.upper(),
                name=name,
                points_value=points_value,
                max_uses_per_user=max_uses_per_user,
                is_public=is_public,
                valid_from=valid_from,
                valid_until=valid_until,
                status=Coupon.StatusChoices.ACTIVE
            )
            
            self.invalidate_public_active_coupons_cache()
            
            # Log admin action
            from api.admin.models import AdminActionLog
            AdminActionLog.objects.create(
                admin_user=admin_user,
                action_type='CREATE_COUPON',
                target_model='Coupon',
                target_id=str(coupon.id),
                changes={
                    'code': code,
                    'name': name,
                    'points_value': points_value,
                    'max_uses_per_user': max_uses_per_user,
                    'is_public': is_public,
                },
                description=f"Created coupon: {code}",
                ip_address="127.0.0.1",
                user_agent="Admin Panel"
            )
            
            self.log_info(f"Coupon created: {code}")
            return coupon
            
        except Exception as e:
            self.handle_service_error(e, "Failed to create coupon")
    
    @transaction.atomic
    def bulk_create_coupons(self, name_prefix: str, points_value: int, max_uses_per_user: int,
                           valid_from: timezone.datetime, valid_until: timezone.datetime,
                           quantity: int, code_length: int, admin_user,
                           is_public: bool = True) -> List[Coupon]:
        """Bulk create coupons (Admin)"""
        try:
            created_coupons = []
            
            for i in range(quantity):
                # Generate unique code
                while True:
                    code = self._generate_coupon_code(code_length)
                    if not Coupon.objects.filter(code=code).exists():
                        break
                
                coupon = Coupon(
                    code=code,
                    name=f"{name_prefix} #{i+1}",
                    points_value=points_value,
                    max_uses_per_user=max_uses_per_user,
                    is_public=is_public,
                    valid_from=valid_from,
                    valid_until=valid_until,
                    status=Coupon.StatusChoices.ACTIVE
                )
                created_coupons.append(coupon)
            
            # Bulk create
            Coupon.objects.bulk_create(created_coupons)
            
            self.invalidate_public_active_coupons_cache()
            
            # Log admin action
            from api.admin.models import AdminActionLog
            AdminActionLog.objects.create(
                admin_user=admin_user,
                action_type='BULK_CREATE_COUPONS',
                target_model='Coupon',
                target_id='bulk',
                changes={
                    'name_prefix': name_prefix,
                    'points_value': points_value,
                    'quantity': quantity,
                    'is_public': is_public,
                },
                description=f"Bulk created {quantity} coupons",
                ip_address="127.0.0.1",
                user_agent="Admin Panel"
            )
            
            self.log_info(f"Bulk created {quantity} coupons with prefix: {name_prefix}")
            return created_coupons
            
        except Exception as e:
            self.handle_service_error(e, "Failed to bulk create coupons")
    
    def _generate_coupon_code(self, length: int) -> str:
        """Generate random coupon code"""
        # Use only safe characters (exclude confusing ones: 0, O, I, 1)
        safe_chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
        return ''.join(random.choices(safe_chars, k=length))
    
    def get_coupons_list(self, filters: Dict[str, Any] = None) -> Dict[str, Any]:
        """Get paginated list of coupons with filters (Admin)"""
        try:
            queryset = Coupon.objects.all()
            
            # Apply filters
            if filters:
                if filters.get('status'):
                    queryset = queryset.filter(status=filters['status'])
                
                if filters.get('search'):
                    search_term = filters['search']
                    queryset = queryset.filter(
                        Q(code__icontains=search_term) |
                        Q(name__icontains=search_term)
                    )

                if filters.get('is_public') is not None:
                    queryset = queryset.filter(is_public=filters['is_public'])
                
                if filters.get('start_date'):
                    queryset = queryset.filter(valid_from__gte=filters['start_date'])
                
                if filters.get('end_date'):
                    queryset = queryset.filter(valid_until__lte=filters['end_date'])
            
            # Order by latest first
            queryset = queryset.order_by('-created_at')
            
            # Pagination
            page = filters.get('page', 1) if filters else 1
            page_size = filters.get('page_size', 20) if filters else 20
            
            return paginate_queryset(queryset, page, page_size)
            
        except Exception as e:
            self.handle_service_error(e, "Failed to get coupons list")
