# Generated by Django 5.2.5 on 2026-01-29 14:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        ('rentals', '0005_extend_lat_lng_precision'),
        ('stations', '0006_extend_lat_lng_precision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StationPackageDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_total_uses', models.IntegerField(blank=True, help_text='Maximum total uses across all users. NULL = unlimited', null=True)),
                ('max_uses_per_user', models.IntegerField(default=1, help_text='Maximum uses per user')),
                ('current_usage_count', models.IntegerField(default=0, help_text='Current total usage count')),
                ('valid_from', models.DateTimeField(help_text='Discount valid from this date/time')),
                ('valid_until', models.DateTimeField(help_text='Discount valid until this date/time')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discounts', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_discounts', to='rentals.rentalpackage')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_discounts', to='stations.station')),
            ],
            options={
                'verbose_name': 'Station Package Discount',
                'verbose_name_plural': 'Station Package Discounts',
                'db_table': 'station_package_discounts',
                'indexes': [models.Index(fields=['station', 'status'], name='station_pac_station_f17f5c_idx'), models.Index(fields=['valid_from', 'valid_until'], name='station_pac_valid_f_0cd2cf_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='discount_percent_range'), models.CheckConstraint(condition=models.Q(('valid_until__gt', models.F('valid_from'))), name='valid_date_range')],
                'unique_together': {('station', 'package')},
            },
        ),
    ]
