# Generated by Django 5.2.5 on 2026-02-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_add_station_package_discounts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together=set(),
        ),
    ]
