# Generated by Django 5.2.5 on 2026-01-06 21:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
        ('users', '0008_remove_userpoints_user_delete_userauditlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='UserPoints',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('current_points', models.IntegerField(default=0)),
                        ('total_points', models.IntegerField(default=0)),
                        ('last_updated', models.DateTimeField(auto_now=True)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'User Points',
                        'verbose_name_plural': 'User Points',
                        'db_table': 'user_points',
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
