# Generated by Django 5.2.5 on 2026-01-06 21:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateFeeConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Choose a clear name for this fee setting (e.g., 'Standard Late Fee' or 'Holiday Double Rate')", max_length=100)),
                ('fee_type', models.CharField(choices=[('MULTIPLIER', 'Multiplier (e.g., 2x normal rate)'), ('FLAT_RATE', 'Flat rate per hour'), ('COMPOUND', 'Compound (multiplier + flat rate)')], default='MULTIPLIER', help_text='Choose how to calculate late fees.', max_length=50)),
                ('multiplier', models.DecimalField(decimal_places=2, default=2.0, help_text='If using MULTIPLIER or COMPOUND fee type.', max_digits=5)),
                ('flat_rate_per_hour', models.DecimalField(decimal_places=2, default=0, help_text='If using FLAT_RATE or COMPOUND fee type.', max_digits=10)),
                ('grace_period_minutes', models.IntegerField(default=0, help_text='How many minutes late before charges start applying.')),
                ('max_daily_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum late fee per day (optional safety limit).', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only ONE late fee configuration can be active at a time.')),
                ('applicable_package_types', models.JSONField(default=list, help_text='Advanced: Limit this configuration to specific rental package types.')),
                ('metadata', models.JSONField(default=dict, help_text='Advanced system information. Usually leave empty.')),
            ],
            options={
                'verbose_name': 'Late Fee Configuration',
                'verbose_name_plural': 'Late Fee Configurations',
                'db_table': 'late_fee_configurations',
                'ordering': ['-created_at'],
            },
        ),
    ]
