# Generated by Django 5.2.5 on 2026-01-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_add_pending_popup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentallocation',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
        migrations.AlterField(
            model_name='rentallocation',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
