# Generated by Django 5.2.5 on 2026-01-30 19:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_extend_lat_lng_precision'),
        ('stations', '0006_extend_lat_lng_precision'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalSwap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_battery_level', models.IntegerField()),
                ('new_battery_level', models.IntegerField()),
                ('swap_reason', models.CharField(choices=[('LOW_BATTERY', 'Low Battery'), ('DEFECTIVE', 'Defective Powerbank'), ('WRONG_CABLE', 'Wrong Cable Type'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('swapped_at', models.DateTimeField(auto_now_add=True)),
                ('new_powerbank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swapped_to', to='stations.powerbank')),
                ('new_slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swapped_to', to='stations.stationslot')),
                ('old_powerbank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swapped_from', to='stations.powerbank')),
                ('old_slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swapped_from', to='stations.stationslot')),
                ('original_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_swaps', to='stations.station')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to='rentals.rental')),
            ],
            options={
                'verbose_name': 'Rental Swap',
                'verbose_name_plural': 'Rental Swaps',
                'db_table': 'rental_swaps',
                'indexes': [models.Index(fields=['rental', 'swapped_at'], name='rental_swap_rental__559288_idx'), models.Index(fields=['original_station', 'swapped_at'], name='rental_swap_origina_6f4569_idx')],
            },
        ),
    ]
