# Generated by Django 5.2.5 on 2026-01-31 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_add_rental_swap_model'),
        ('stations', '0007_powerbank_total_cycles_powerbank_total_rentals'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='hardware_issue_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='is_under_5_min',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='return_battery_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='start_battery_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BatteryCycleLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_level', models.IntegerField()),
                ('end_level', models.IntegerField()),
                ('discharge_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cycle_contribution', models.DecimalField(decimal_places=4, max_digits=5)),
                ('powerbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_logs', to='stations.powerbank')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_logs', to='rentals.rental')),
            ],
            options={
                'verbose_name': 'Battery Cycle Log',
                'verbose_name_plural': 'Battery Cycle Logs',
                'db_table': 'battery_cycle_logs',
                'indexes': [models.Index(fields=['powerbank', 'created_at'], name='battery_cyc_powerba_64045f_idx'), models.Index(fields=['rental'], name='battery_cyc_rental__ade5fc_idx')],
            },
        ),
    ]
