# Generated by Django 5.2.5 on 2026-01-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_add_notification_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('rental', 'Rental'), ('payment', 'Payment'), ('promotion', 'Promotion'), ('system', 'System'), ('achievement', 'Achievement'), ('security', 'Security'), ('points', 'Points'), ('update', 'Update'), ('admin', 'Admin'), ('otp_sms', 'OTP SMS'), ('otp_email', 'OTP Email'), ('advertisement', 'Advertisement')], max_length=50),
        ),
    ]
