# Generated by Django 5.2.5 on 2026-01-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_extend_lat_lng_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerbank',
            name='total_cycles',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='powerbank',
            name='total_rentals',
            field=models.IntegerField(default=0),
        ),
    ]
