# Generated by Django 5.2.5 on 2026-01-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_add_withdrawal_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='refund_id',
            field=models.CharField(blank=True, help_text='Unique refund identifier', max_length=50, null=True, unique=True),
        ),
    ]
