# Generated by Django 5.2.9 on 2026-01-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_refund_refund_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
