# Generated by Django 5.2.9 on 2026-01-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_withdrawalrequest_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('TOPUP', 'Top Up'), ('RENTAL', 'Rental'), ('RENTAL_DUE', 'Rental Due'), ('REFUND', 'Refund'), ('FINE', 'Fine'), ('ADVERTISEMENT', 'Advertisement')], max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=50),
        ),
    ]
