# Generated by Django 5.2.5 on 2026-02-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Payment method icon URL or asset path', max_length=255),
        ),
    ]
