# Generated by Django 5.2.5 on 2026-01-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_social_profile_data'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='userpoints',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='UserPoints',
                ),
            ],
            database_operations=[],
        ),
        migrations.DeleteModel(
            name='UserAuditLog',
        ),
    ]
