# Generated by Django 5.2.5 on 2026-01-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_userpoints_user_delete_userauditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='biometric_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='biometric_last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='biometric_registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='biometric_token',
            field=models.CharField(blank=True, db_index=True, help_text='Secure token for biometric authentication', max_length=512, null=True, unique=True),
        ),
    ]
