# Generated by Django 5.2.9 on 2026-01-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userdevice_biometric_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_partner',
            field=models.BooleanField(default=False, help_text='True if user is a partner (Franchise/Vendor) - enables password auth'),
        ),
    ]
