# Generated by Django 5.2.5 on 2026-04-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userkyc_font_face_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='device_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='userdevice',
            unique_together={('user', 'device_id')},
        ),
    ]
