"""
Biometric Authentication Views
==============================
Views for biometric authentication operations
"""
import logging
from drf_spectacular.utils import extend_schema, OpenApiParameter
from rest_framework import status
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.request import Request
from rest_framework.response import Response

from api.common.routers import CustomViewRouter
from api.common.mixins import BaseAPIView
from api.common.decorators import rate_limit, log_api_call
from api.common.serializers import BaseResponseSerializer
from api.user.auth.serializers import biometric_serializers
from api.user.auth.services.biometric_auth_service import BiometricAuthService

biometric_router = CustomViewRouter()
logger = logging.getLogger(__name__)


@biometric_router.register(r"auth/biometric/enable", name="biometric-enable")
@extend_schema(
    tags=["Authentication - Biometric"],
    summary="Enable Biometric Authentication",
    description="Enable biometric login for the current device. "
                "Requires user to be authenticated via OTP first. "
                "App must generate a secure random token (min 256-bit) and store it securely."
)
class BiometricEnableView(GenericAPIView, BaseAPIView):
    serializer_class = biometric_serializers.BiometricEnableSerializer
    permission_classes = [IsAuthenticated]
    
    @extend_schema(
        summary="Enable Biometric for Device",
        description="Enable biometric authentication for the current device. "
                    "The biometric_token should be a cryptographically secure random string "
                    "(minimum 32 characters, 256-bit recommended) generated by the app and "
                    "stored in secure storage (iOS Keychain / Android Keystore).",
        request=biometric_serializers.BiometricEnableSerializer,
        responses={
            200: BaseResponseSerializer,
            400: BaseResponseSerializer
        }
    )
    @log_api_call(include_request_data=True)
    def post(self, request: Request) -> Response:
        """Enable biometric for device"""
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        
        return self.handle_service_operation(
            lambda: BiometricAuthService().enable_biometric(
                user=request.user,
                device_id=serializer.validated_data['device_id'],
                biometric_token=serializer.validated_data['biometric_token']
            ),
            success_message="Biometric enabled successfully"
        )



@biometric_router.register(r"auth/biometric/login", name="biometric-login")
@extend_schema(
    tags=["Authentication - Biometric"],
    summary="Login with Biometric",
    description="Login using biometric authentication. "
                "Returns JWT access and refresh tokens on successful authentication."
)
class BiometricLoginView(GenericAPIView, BaseAPIView):
    serializer_class = biometric_serializers.BiometricLoginSerializer
    permission_classes = [AllowAny]
    
    @extend_schema(
        summary="Biometric Login",
        description="Authenticate user using biometric credentials. "
                    "App should verify biometric locally first, then send the stored token. "
                    "Returns JWT tokens on success.",
        request=biometric_serializers.BiometricLoginSerializer,
        responses={
            200: BaseResponseSerializer,
            400: BaseResponseSerializer,
            401: BaseResponseSerializer
        }
    )
    @rate_limit(max_requests=5, window_seconds=300)
    @log_api_call(include_request_data=True)
    def post(self, request: Request) -> Response:
        """Login using biometric"""
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        
        return self.handle_service_operation(
            lambda: BiometricAuthService().biometric_login(
                device_id=serializer.validated_data['device_id'],
                biometric_token=serializer.validated_data['biometric_token'],
                request=request
            ),
            success_message="Biometric login successful"
        )


@biometric_router.register(r"auth/biometric/disable", name="biometric-disable")
@extend_schema(
    tags=["Authentication - Biometric"],
    summary="Disable Biometric Authentication",
    description="Disable biometric login for the current device. "
                "User must be authenticated to disable biometric."
)
class BiometricDisableView(GenericAPIView, BaseAPIView):
    serializer_class = biometric_serializers.BiometricDisableSerializer
    permission_classes = [IsAuthenticated]
    
    @extend_schema(
        summary="Disable Biometric for Device",
        description="Disable biometric authentication for the specified device. "
                    "App should also delete the locally stored token after successful disable.",
        request=biometric_serializers.BiometricDisableSerializer,
        responses={
            200: BaseResponseSerializer,
            400: BaseResponseSerializer
        }
    )
    @log_api_call(include_request_data=True)
    def post(self, request: Request) -> Response:
        """Disable biometric for device"""
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        
        return self.handle_service_operation(
            lambda: BiometricAuthService().disable_biometric(
                user=request.user,
                device_id=serializer.validated_data['device_id']
            ),
            success_message="Biometric disabled successfully"
        )


@biometric_router.register(r"auth/biometric/status", name="biometric-status")
@extend_schema(
    tags=["Authentication - Biometric"],
    summary="Check Biometric Status",
    description="Check if biometric is enabled for a specific device",
    parameters=[
        OpenApiParameter(
            name='device_id',
            type=str,
            location=OpenApiParameter.QUERY,
            required=True,
            description='Device ID to check biometric status for'
        )
    ],
    responses={
        200: BaseResponseSerializer,
        400: BaseResponseSerializer
    }
)
class BiometricStatusView(GenericAPIView, BaseAPIView):
    permission_classes = [IsAuthenticated]
    
    @log_api_call()
    def get(self, request: Request) -> Response:
        """Get biometric status for device"""
        device_id = request.query_params.get('device_id')
        if not device_id:
            return Response(
                {
                    'success': False,
                    'error': {
                        'code': 'validation_error',
                        'message': 'device_id query parameter is required'
                    }
                },
                status=status.HTTP_400_BAD_REQUEST
            )
        
        return self.handle_service_operation(
            lambda: BiometricAuthService().get_biometric_status(
                user=request.user,
                device_id=device_id
            ),
            success_message="Biometric status retrieved"
        )
