# Generated by Django 5.2.9 on 2026-01-17 07:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('payments', '0011_alter_transaction_transaction_type_and_more'),
        ('stations', '0006_extend_lat_lng_precision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(help_text='Full name of the advertiser', max_length=255)),
                ('contact_number', models.CharField(help_text='Contact number for the advertiser', max_length=50)),
                ('title', models.CharField(blank=True, help_text='Ad title (set by admin)', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Ad description (set by admin)', null=True)),
                ('duration_days', models.IntegerField(blank=True, help_text='Duration in days (set by admin)', null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid'), ('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', help_text='Current status of the ad request', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the ad was submitted', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the ad was reviewed', null=True)),
                ('admin_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price set by admin', max_digits=12, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about the ad', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if rejected', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the ad was approved', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was received', null=True)),
                ('start_date', models.DateField(blank=True, help_text='When ad starts running', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When ad ends', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When ad was completed', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved the ad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ads', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed the ad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ads', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, help_text='Payment transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_requests', to='payments.transaction')),
                ('user', models.ForeignKey(help_text='User who submitted the ad request', on_delete=django.db.models.deletion.CASCADE, related_name='ad_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ad Request',
                'verbose_name_plural': 'Ad Requests',
                'db_table': 'ad_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], help_text='Type of content (IMAGE or VIDEO)', max_length=10)),
                ('duration_seconds', models.IntegerField(default=5, help_text='Display duration for images (in seconds)')),
                ('display_order', models.IntegerField(default=0, help_text='Order in rotation (lower = higher priority)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this content is active')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('media_upload', models.ForeignKey(help_text='Uploaded media file', on_delete=django.db.models.deletion.PROTECT, related_name='ad_contents', to='media.mediaupload')),
                ('ad_request', models.ForeignKey(help_text='Parent ad request', on_delete=django.db.models.deletion.CASCADE, related_name='ad_contents', to='advertisements.adrequest')),
            ],
            options={
                'verbose_name': 'Ad Content',
                'verbose_name_plural': 'Ad Contents',
                'db_table': 'ad_contents',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_content', models.ForeignKey(help_text='Ad content to distribute', on_delete=django.db.models.deletion.CASCADE, related_name='ad_distributions', to='advertisements.adcontent')),
                ('station', models.ForeignKey(help_text='Station where ad will be displayed', on_delete=django.db.models.deletion.CASCADE, related_name='ad_distributions', to='stations.station')),
            ],
            options={
                'verbose_name': 'Ad Distribution',
                'verbose_name_plural': 'Ad Distributions',
                'db_table': 'ad_distributions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ad_content', 'station'], name='ad_distribu_ad_cont_da3850_idx'), models.Index(fields=['station', 'created_at'], name='ad_distribu_station_e8f4c8_idx')],
                'unique_together': {('ad_content', 'station')},
            },
        ),
        migrations.AddIndex(
            model_name='adrequest',
            index=models.Index(fields=['user', 'status'], name='ad_requests_user_id_745f0b_idx'),
        ),
        migrations.AddIndex(
            model_name='adrequest',
            index=models.Index(fields=['status', 'start_date'], name='ad_requests_status_6078ab_idx'),
        ),
        migrations.AddIndex(
            model_name='adrequest',
            index=models.Index(fields=['status', 'end_date'], name='ad_requests_status_1b9492_idx'),
        ),
        migrations.AddIndex(
            model_name='adrequest',
            index=models.Index(fields=['status', 'paid_at'], name='ad_requests_status_359aab_idx'),
        ),
        migrations.AddIndex(
            model_name='adrequest',
            index=models.Index(fields=['user', 'created_at'], name='ad_requests_user_id_0049e4_idx'),
        ),
        migrations.AddIndex(
            model_name='adcontent',
            index=models.Index(fields=['ad_request', 'is_active'], name='ad_contents_ad_requ_6491b1_idx'),
        ),
        migrations.AddIndex(
            model_name='adcontent',
            index=models.Index(fields=['content_type', 'is_active'], name='ad_contents_content_8985e4_idx'),
        ),
    ]
