# Generated by Django 5.2.5 on 2026-04-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcontent',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='Click-through redirect URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='adcontent',
            name='url_large',
            field=models.URLField(blank=True, help_text='URL for ad when station has >= 20 slots (large screen)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='adcontent',
            name='url_small',
            field=models.URLField(blank=True, help_text='URL for ad when station has < 20 slots (small screen)', max_length=500, null=True),
        ),
    ]
