# Generated by Django 5.2.5 on 2026-04-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_adcontent_redirect_url_adcontent_url_large_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrequest',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='Click-through redirect URL for device tap', max_length=500, null=True),
        ),
    ]
