"""
Biometric Authentication Serializers
====================================
Serializers for biometric authentication endpoints
"""
from rest_framework import serializers


class BiometricEnableSerializer(serializers.Serializer):
    """Enable biometric authentication"""
    device_id = serializers.CharField(
        max_length=255,
        help_text="Unique device identifier"
    )
    biometric_token = serializers.CharField(
        max_length=512,
        min_length=32,
        help_text="Secure token generated by app (min 32 chars, 256-bit recommended)"
    )
    
    def validate_biometric_token(self, value):
        if len(value) < 32:
            raise serializers.ValidationError(
                "Biometric token must be at least 32 characters"
            )
        return value


class BiometricLoginSerializer(serializers.Serializer):
    """Login with biometric"""
    device_id = serializers.CharField(
        max_length=255,
        help_text="Unique device identifier"
    )
    biometric_token = serializers.CharField(
        max_length=512,
        help_text="Biometric token stored on device"
    )


class BiometricDisableSerializer(serializers.Serializer):
    """Disable biometric authentication"""
    device_id = serializers.CharField(
        max_length=255,
        help_text="Unique device identifier"
    )
