# Generated by Django 5.2.5 on 2026-02-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If true, this config is exposed by public app config endpoint.'),
        ),
    ]
